### ISSUE TITLE
Add @supports support

### ISSUE THREAD

**Issue by blicksky** [rofrischmann/inline-style-prefixer#138]
I'm wondering if any thought has been put into supporting `@supports`, and possibly other at-rules like `@keyframes`. This would avoid the situations like the following, where you still have to know and manually specify all the prefixed properties that could be automatically substituted.

```css
@supports((-webkit-appearance: none) or (-moz-appearance: none) or (appearance: none)) {
    appearance: none;
}
```

[autoprefixer](https://github.com/postcss/autoprefixer#write-pure-css) claims to support it, but I haven't tried it out myself.
